### ISSUE TITLE
Design Thinking: submitting jobs

### ISSUE THREAD

**Issue by vsoch** [converged-computing/ensemble-operator#6]
I'm looking at a traditional "submit this job" minicluster, e.g., here is the current lammps:

```yaml
apiVersion: ensemble.flux-framework.org/v1alpha1
kind: Ensemble
metadata:
  name: ensemble-sample
spec:
  members:
  - minicluster:
      spec:

        size: 2
        maxSize: 4
        minSize: 2
        tasks: 2
    
        # This is a list because a pod can support multiple containers
        containers:
        - image: ghcr.io/converged-computing/metric-lammps:latest

          # You can set the working directory if your container WORKDIR is not correct.
          workingDir: /opt/lammps/examples/reaxff/HNS
          batchRaw: true
          batch: true
          commands:
            post: sleep infinity
          command: |
             lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
             sleep infinity
```
And there are several things that I don't like.

- The user is required to have specialized knowledge about flux to submit a job given some algorithm (e.g., ask to make a batch job vs not, waitable vs not).
- It would also require the user to understand the difference between a "submit to queue now" vs. "set the priority to 0 so it doesn't run"
- The CRD is long and kind of messy - it could be simpler.
- (And the biggest issue, imho) is that using batch is going to spit out a job id, and the job id is going to point to another file with job ids, and easily getting output and even the job ids is really annoying.

You can imagine actually trying to submit jobs in that batch directive, it's going to be long and ugly very quickly, and you won't easily see jobids or output.

```console
# Submit a bunch of lammps jobs (would be nice to have a language to do this)
# Or do in some gnary for loops... noooo
flux submit lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
flux submit lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
flux submit lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
flux submit lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
sleep infinity
```

Since we already have a planned design for the operator to take charge of handling the submission, why not make this the default? It would mean a CRD is simplified to this:

```yaml
apiVersion: ensemble.flux-framework.org/v1alpha1
kind: Ensemble
metadata:
  name: workload-demand
spec:
  members:
  - algorithm:
      name: workload-demand
    minicluster:
      spec:
        size: 2
        maxSize: 10
        minSize: 2

        # This is a list because a pod can support multiple containers
        containers:
        - image: ghcr.io/converged-computing/metric-lammps:latest

          # You can set the working directory if your container WORKDIR is not correct.
          workingDir: /opt/lammps/examples/reaxff/HNS
```

In the above, what isn't seen is that the ensemble operator will set interactive to true, meaning we are starting a broker within the flux minicluster that is waiting. Given that the broker is running, we can then be in charge of submitting jobs! And this means that regardless of our strategy (submit everything at once and react vs. controlled submission) the CRD can look the same. I haven't written this yet (will do soon, although going outside to run soon) but I'm thinking of something like:

```yaml
apiVersion: ensemble.flux-framework.org/v1alpha1
kind: Ensemble
metadata:
  name: workload-demand
spec:
  members:
  - sidecarPullAlways: true
    algorithm:
      name: workload-demand
    jobs:
      - name: lammps-2
        command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
        count: 10
      - name: lammps-4
        command: lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
        count: 5

    minicluster:
      spec:
        size: 2
        maxSize: 10
        minSize: 2

        # This is a list because a pod can support multiple containers
        containers:
        - image: ghcr.io/converged-computing/metric-lammps:latest

          # You can set the working directory if your container WORKDIR is not correct.
          workingDir: /opt/lammps/examples/reaxff/HNS
```
I like this design for the following reasons:

- We can easily add the category labels to the jobs that I described in a few algorithms that build models according to said labels.
- We can also eventually add different metadata about the runs.
- I also like that design because it means (hypothetically) the same jobs matrix could work between member types (if/when we ever get to that). 

The label might look like this - "build a model for all lammps, and all amg across sizes"

```yaml
    jobs:
      - name: lammps-2
        command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
        count: 10
        label: lammps
      - name: lammps-4
        command: lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
        count: 5
        label: lammps
      - name: amg
        command: amg ...
        count: 100
        label: amg
```

And actually that is generic, because technically speaking (if we do this right) the algorithm should be able to use the label as a meaningful group for whatever it needs to do. It likely could correspond to a new model or a loaded (existing) model. It could be a way to retrieve metadata from somewhere else on the fly. Really the detail we need to get right is the specification of the jobs - what does an ensemble request look like? The above is kind of stupid and simple, but that's OK, we can work on it.
